### ISSUE TITLE
i7

### ISSUE THREAD

**Issue by DrPandemic** [JDIS/static-website#18]
Thanks for the reordering. We should ask @Sytten to see if we could have another element for the i7. I don't like the fact that i5 has 5 elements and i7 has 4 and a x at the end. It's just about the presentation.

**Comment by DrPandemic** [comment]
> Agreed! Also, IMHO, the X implies that a feature is not included. You know, something like this.
> ![2015-12-28-200724_664x239_scrot](https://cloud.githubusercontent.com/assets/8457808/12028036/a23e5ad2-ad9e-11e5-8ef2-bcfa76519d63.png)
> How about we just remove the X (or replace it with something that doesn't imply a disadvantage)?

**Comment by maximevaillancourt** [comment]
Another thing: on mobile, the Xs don't make sense at all.
![12465231_1501578793470475_218656612_o](https://cloud.githubusercontent.com/assets/8457808/12039240/9bdb376c-ae2c-11e5-8221-87fd03564386.jpg)
