### ISSUE TITLE
Non square images break layout (events, sponsors)

### ISSUE THREAD

**Issue by maximevaillancourt** [JDIS/static-website#19]
See this: https://github.com/JDIS/static-website/pull/17#issuecomment-167835552

**Comment by Sytten** [comment]
Can we make a pull request for that?

**Comment by DrPandemic** [comment]
I put this on my todo

**Comment by DrPandemic** [comment]
Ok, my solution was causing more problem than it was fixing. I really have a hard time understanding how everything is working there for the responsive images. Is there some JS that is managing the sizes?

Anyway, I would argue that simply putting square images is simpler that making this fix. So if no-one is against that I will close this issue.

**Comment by maximevaillancourt** [comment]
LGTM
