### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by maximevaillancourt** [JDIS/static-website#22]
Are the CSS animations really necessary? It seems to me that they just slow down the website without really adding value. It really doesn't feel snappy, especially on mobile. How about we remove them?

**Comment by Sytten** [comment]
They do slow down the website a bit, but their are also nice. Maybe we should only disable them on small screens. Want to create a branch for that? (Off topic: maybe we should close the other unused branches)

**Comment by maximevaillancourt** [comment]
They _are_ nice, but they don't feel snappy. I think simply reducing the animation time would greatly help. I'm off to delete to unused branches.

**Comment by Sytten** [comment]
We should try. I agree that we maybe have too many animations, but none would kinda of boring.

**Comment by maximevaillancourt** [comment]
I'll try to speed up some of them so that it feels snappier.

**Comment by DrPandemic** [comment]
:+1:

**Comment by maximevaillancourt** [comment]
Fixed. They are quicker now.
