### ISSUE TITLE
Huge header logo

### ISSUE THREAD

**Issue by maximevaillancourt** [JDIS/static-website#23]
For a first-time visitor on the site, it's unclear that they should click the logo or scroll down to see the website. The original theme (Codeon) has a button, which clearly tells the user to click it and go somewhere. It's not the case on our website. We could replace the huge logo with a photo banner, or just add a button to tell the user he has to do something.

Here's the original theme use-case.
![capture](https://cloud.githubusercontent.com/assets/8457808/12401083/1b62921c-bdf2-11e5-8a34-0a99763068d7.PNG)

**Comment by Sytten** [comment]
Maybe we could reduce a bit the size of the logo and add an arrow pointing down. Actually when you click the logo it scrolls down...

**Comment by maximevaillancourt** [comment]
I know that, but a first-time user might not, hence the usefulness of an action trigger such as a button or an arrow. I'll try something new for the header in a pull request, you'll judge for yourself.

**Comment by Sytten** [comment]
Merged
