### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by maximevaillancourt** [JDIS/static-website#28]
Even though our website's a static one-pager, we could add SSL support using Cloudflare's free SSL certificates. I did for my personal website, also hosted on GitHub Pages with a custom domain. Here are instructions on how to do it:
- https://me.net.nz/blog/github-pages-secure-with-cloudflare/
- https://blog.keanulee.com/2014/10/11/setting-up-ssl-on-github-pages.html
- https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

There's one drawback, though (still, it's a lot better than _not_ having SSL):

> the connection between CloudFlare and GitHub pages is not secured. Since GitHub doesn’t have a SSL certificate for your domain, Full SSL is not possible with a custom domain.

**Comment by Sytten** [comment]
Well its a lot of work for none sensitive information (except maybe the contact form and email)
If I have time, I will setup it. Probably one night this week.

**Comment by maximevaillancourt** [comment]
If you allow me to access our registrar's admin dashboard, I'll add SSL support later this week.

**Comment by Sytten** [comment]
Try to talk to david about that

**Comment by maximevaillancourt** [comment]
pinging @carapas!
