### ISSUE TITLE
Clicking on "Partners" in the nav links to the "wrong" section

### ISSUE THREAD

**Issue by maximevaillancourt** [JDIS/static-website#31]
When clicking on "Partners" in the top navigation bar, it links to the "Sponsoring Plans" section, which technically, is the right place (the `<a>` links there), but logically, it's not. We could simply move the `id` to the right place.
![capture](https://cloud.githubusercontent.com/assets/8457808/12409532/ee0ab0f0-be38-11e5-9f7a-ba69fbc5e61e.PNG)

**Comment by Sytten** [comment]
Done
