### ISSUE TITLE
Update template

### ISSUE THREAD

**Issue by Sytten** [JDIS/static-website#33]
Just saw that they updated the template (codeon).
I dont know if we have access to these changes, but it would be great to merge them if possible.

https://wrapbootstrap.com/theme/codeon-multi-purpose-one-page-theme-WB01589G9

**Comment by maximevaillancourt** [comment]
Since we removed a lot of stuff from the Codeon template and added our own, I don't think it's worth merging the changes. We now have our very own template. What do you think?

**Comment by Sytten** [comment]
Yea I guess
