### ISSUE TITLE
Fix scrolling performance (fixed bg, parallax issues)

### ISSUE THREAD

**Issue by maximevaillancourt** [JDIS/static-website#36]
Our website suffers from poor scrolling performance. In the original theme (Codeon) we use, there are sections with parallaxing backgrounds. Even though we removed these backgrounds, the parallax action still happens (it simply parallaxes nothing), and the CSS is still there. Because of this, the whole page redraws every time we scroll. We should remove the parallax bits of the website to improve performance.

I originally thought poor performance was caused by using too many animations (#22), when in fact, it's caused by the constant repainting of the page.

Also, the issue can be reproduced on Firefox and Chrome. MS Edge looks fine (silky smooth scrolling, yay!).

Relevant: http://fourkitchens.com/blog/article/fix-scrolling-performance-css-will-change-property

**Comment by Sytten** [comment]
Hooo, nice finding :+1: 
Should be easy to fix?

**Comment by maximevaillancourt** [comment]
The `will-change` attribute asks the browser to redraw the element independently. However, the Mozilla Docs state that it should be used sparingly, since the browser already tries its best to optimize page redraws.

Solution 1 would be to remove all traces of parallaxing (since we don't currently use it anyway). `background-size: cover` is the main source of repainting. Solution 2 would be to use `transform: translateZ(0);` to force the repainting to happen on the GPU, but this is considered to be a not-so-clean hack. Thus, I propose solution 1.

**Comment by Sytten** [comment]
I agree we can remove it.

**Comment by maximevaillancourt** [comment]
The Stellar plugin is responsible for the poor performance. I propose removing the plugin altogether.

It's a matter of removing the .js file, as well as cleaning the HTML and CSS from any mention of Stellar classes.

**Comment by maximevaillancourt** [comment]
Somewhat fixed: our carousel relies on Stellar, so we have to keep it as long as the carousel's around. However, I replaced the "parallax" classes where they weren't necessary.
