### ISSUE TITLE
Change design and content of sponsorship plan

### ISSUE THREAD

**Issue by Sytten** [JDIS/static-website#45]
-We need to change some texts
-Change the design, not very beautiful right now

**Comment by maximevaillancourt** [comment]
How it looks right now, for reference:
![dacdbf96-ccd9-11e5-820b-f01188d439cb 1](https://cloud.githubusercontent.com/assets/8457808/12868871/90f0cf8a-ccde-11e5-9710-e3909dd5a365.png)

**Comment by carapas** [comment]
Looks really good!

**Comment by maximevaillancourt** [comment]
I think it looks nice as well. @Sytten, what would you change?

**Comment by Sytten** [comment]
nothing all fine lol
