### ISSUE TITLE
Small modification to the sponsorship plan

### ISSUE THREAD

**Issue by Sytten** [JDIS/static-website#62]
We need two small modifications (to be confirmed):
-Add an exception to the I7 plan (internal events except the JDIS conference)
-Add a precision for the Xenon plan (invitation to the conference with the advantages of the 500$ plan)

**Comment by maximevaillancourt** [comment]
Let us know if/when this is confirmed.

**Comment by Sytten** [comment]
Will have to talk about that next CE

**Comment by maximevaillancourt** [comment]
@Sytten, any news on that?

**Comment by Sytten** [comment]
We can't change that until the end of 2016
